version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data